Nuget cleanup
Baseflow/DSTV.Net pull request #3
Opened 2023-06-05 07:45 UTC by martijn00

2023-06-20 14:48 UTC, tluijken requested changes
I'm getting issues on the IDisposable analyzer when building the project.

CSC : error CS9057: The analyzer assembly '\~/packages/idisposableanalyzers/4.0.6/analyzers/dotnet/cs/IDisposableAnalyzers.dll' references version '4.5.0.0' of the compiler, which is newer than the currently running version '4.4.0.0'. [\~/projects/baseflow/DSTVReader/DSTV.Net/DSTV.Net.csproj]

Do you know why? I have dotnet SDK 6.0.100, 6.0.116 and 7.0.105 installed on my machine.
I ran:
```shell
dotnet clean
dotnet restore
dotnet build
```

2023-06-20 14:48 UTC, tluijken commented on DSTV.Net/Extensions/TextReaderExtensions.cs
> +    /// <typeparam name="TEnum"></typeparam>
Als we m toevoegen, moeten we m eigenlijk ook vullen met wat zinnige informatie. Wat is de betekening van TEnum hier?

2023-07-03 12:52 UTC, martijn00 commented on DSTV.Net/Implementations/HeaderReader.cs
> +    [System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "MA0051:Method is too long", Justification = "<Pending>")]
Hmm not sure. Maybe just fix it later whenever anyone feels like it?

2023-07-03 12:52 UTC, martijn00 commented
@tluijken I don't know, for me it builds fine on mac and windows.

2023-08-28 10:34 UTC, merged